[features]
seeds = false
skip-lint = false
[programs.localnet]
secure_voting = "4FWXDxhLGqGvdG3gbeS7PqXBoQFqsDBcWa1Bp578PamE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/max/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
